### PR TITLE
Sammcdo/3/drivebase

### PR DESCRIPTION
**Pull request by sammcdo**

### CODE REVIEW

**Review by ghost — DISMISSED** [review]
lots of original comments, but I think we can clean that up later in a cleanup branch

**Review by EliSauder — DISMISSED** [review]
Looks pretty good. Just a few comments.

Make sure you are commenting your code with what it does.

**Review by ghost — APPROVED** [review]
cool, where's pixycam?

**Review by ghost — DISMISSED** [review]

**Review by ghost — APPROVED** [review]
thanks for the comments

**Review by ghost — DISMISSED** [review]

**Comment by EliSauder** [comment]
Closed in favor of working towards the 2020 season.

**Pull request closed without merging**
